Repository kubernetes/cloud-provider-alibaba-cloud, pull requests merged in 2018-12, with the labels that each got.

#15 add zh doc
  docs/zh/usage.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#17 Add CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#18 Add SECURITY_CONTACTS
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/S
