Repository kubernetes/cloud-provider-alibaba-cloud, pull requests merged in 2019-11, with the labels that each got.

#113 Ignore to add instance nat ip
  cloud-controller-manager/instances.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#115 fix bug that sync weights from cache can cause dirty data
  cloud-controller-manager/controller/service/context.go
  cloud-controller-manager/controller/service/controller.go
  cloud-controller-manager/listeners.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#116 fix route creation when the node is in unknown status
  cloud-controller-manager/controller/route/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
