Repository kubernetes/cloud-provider-alibaba-cloud, pull requests merged in 2019-09, with the labels that each got.

#87 retry with status log
  cloud-controller-manager/controller/service/controller.go
Labels: cncf-cla: yes, ok-to-test, size/S

#93 support private zone annotation in e2etest framework
  cloud-controller-manager/controller/node/controller.go
  cloud-controller-manager/controller/service/context.go
  cloud-controller-manager/controller/service/controller.go
  cloud-controller-manager/framework.go
  cloud-controller-manager/utils/const.go
  cloud-controller-manager/vgroups.go
  docs/usage.md
  docs/zh/usage.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#94 Add SERVICE_FORCE_BACKEND_ENI env for serverless kubernetes
  cloud-controller-manager/controller/service/context.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#96 Bugfix
  cloud-controller-manager/controller/node/controller.go
  cloud-controller-manager/controller/route/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#98 code refactoring: isEniBackend and IsENIBackendType
  cloud-controller-manager/controller/service/context.go
  cloud-controller-manager/controller/service/controller.go
  cloud-controller-manager/framework.go
  cloud-controller-manager/listeners.go
  cloud-controller-manager/utils/const.go
  cloud-controller-manager/vgroups.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#97 fix bug that endpoint do not have NodeName
  cloud-controller-manager/controller/service/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#100 Remove NodeSyncTask from service controller to avoid concurrency issues
  cloud-controller-manager/controller/service/controller.go
  cloud-controller-manager/framework.go
  cloud-controller-manager/loadbalancer.go
  cloud-controller-manager/utils/const.go
  cloud-controller-manager/vgroups.go
  cmd/cloudprovider/app/ccm.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#102 Minor change for IsENIBackendType
  cloud-controller-manager/utils/const.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
