Repository kubernetes/cloud-provider-alibaba-cloud, pull requests merged in 2019-10, with the labels that each got.

#106 Ignore missing providerid node
  cloud-controller-manager/controller/node/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#107 update zh usage.md
  docs/zh/usage.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#108 Feature/node add description
  cloud-controller-manager/framework.go
  cloud-controller-manager/vgroups.go
  vendor/github.com/denverdino/aliyungo/slb/vserver_group.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#110 batch process for DescribeNetworkInterfaces
  cloud-controller-manager/alicloud_test.go
  cloud-controller-manager/vgroups.go
Labels: cncf-cla: yes, ok-to-test, size/L

#109 Feature/support user managed backend
  cloud-controller-manager/framework.go
  cloud-controller-manager/vgroups.go
  cmd/e2e/test/service.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M
