Repository kubernetes/cloud-provider-alibaba-cloud, pull requests merged in 2019-01, with the labels that each got.

#21 Update getting-started with k8s 1.13 validation
  README.md
  docs/examples/kubeadm-new.conf
  docs/getting-started.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#23 Add LoadBalancer Annotation doc
  README.md
  docs/usage.md
  docs/zh/usage.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#25 Fix typo & pass tag env for build
  Makefile
  docs/zh/usage.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#24 Support LoadBalancer additional tags
  README.md
  cloud-controller-manager/loadbalancer.go
  cloud-controller-manager/loadbalancer_test.go
  cloud-controller-manager/options.go
  cloud-controller-manager/routes.go
  hack/metaserver-deploy.yaml
  hack/metaserver-svc.yaml
  hack/setup.sh
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L
