Repository kubernetes/cloud-provider-alibaba-cloud, pull requests merged in 2019-12, with the labels that each got.

#125 ignore idc node
  cloud-controller-manager/controller/route/controller.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#126 fix typo
  cloud-controller-manager/alicloud_test.go
  cloud-controller-manager/controller/node/controller.go
  cloud-controller-manager/controller/route/controller.go
  cloud-controller-manager/controller/service/controller.go
  cloud-controller-manager/listener_test.go
  cloud-controller-manager/loadbalancer.go
  cloud-controller-manager/loadbalancer_test.go
  cloud-controller-manager/privatezone.go
  cloud-controller-manager/vgroups.go
  docs/testing.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#127 Revert "Feature/support user managed backend"
  cloud-controller-manager/framework.go
  cloud-controller-manager/vgroups.go
  cmd/e2e/test/service.go
Labels: cncf-cla: yes, ok-to-test, size/M

#124 Bugfix/remove ecs serverip
  cloud-controller-manager/listener_test.go
  cloud-controller-manager/listeners.go
  cloud-controller-manager/loadbalancer_mock.go
  cloud-controller-manager/loadbalancer_test.go
  cloud-controller-manager/vgroups.go
  cmd/e2e/test/combination.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#128 delete route when node deleted
  cloud-controller-manager/alicloud.go
  cloud-controller-manager/controller/route/controller.go
  cloud-controller-manager/routes.go
Labels: cncf-cla: yes, ok-to-test, size/L

#134 allow zone field to be empty when reading cloud config
  cloud-controller-manager/clientmgr.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#135 Fix aliyungo concurrent map write. requeue backoff on throttle
  cloud-controller-manager/controller/service/controller.go
  cmd/cloudprovider/app/ccm.go
  vendor/github.com/denverdino/aliyungo/common/endpoint.go
Labels: cncf-cla: yes, ok-to-test, size/M
