Repository kubernetes/cloud-provider-alibaba-cloud, pull requests merged in 2019-07, with the labels that each got.

#62 Servicecontroller
  cloud-controller-manager/alicloud.go
  cloud-controller-manager/alicloud_test.go
  cloud-controller-manager/clientmgr.go
  cloud-controller-manager/controller/node/controller.go
  cloud-controller-manager/controller/route/controller.go
  cloud-controller-manager/controller/service/context.go
  cloud-controller-manager/controller/service/controller.go
  cloud-controller-manager/controller/service/controller_test.go
  cloud-controller-manager/controller/service/service_controller.go
  cloud-controller-manager/framework.go
  cloud-controller-manager/instance_test.go
  cloud-controller-manager/instances.go
  cloud-controller-manager/instances_mock.go
  cloud-controller-manager/listener_test.go
  cloud-controller-manager/listeners.go
  cloud-controller-manager/loadbalancer.go
  cloud-controller-manager/loadbalancer_mock.go
  cloud-controller-manager/loadbalancer_test.go
  cloud-controller-manager/options.go
  cloud-controller-manager/routes_mock.go
  cloud-controller-manager/routes_test.go
  cloud-controller-manager/utils.go
  cloud-controller-manager/vgroups.go
  cmd/cloudprovider/app/ccm.go
  cmd/cloudprovider/app/controllermanager.go
  cmd/cloudprovider/app/options/options.go
  cmd/cloudprovider/cloudprovider-alibaba-cloud.go
  hack/cloud-config.conf
  hack/setup.sh
  vendor/github.com/denverdino/aliyungo/common/client.go
  vendor/github.com/denverdino/aliyungo/common/request.go
  vendor/github.com/denverdino/aliyungo/ecs/eni.go
  vendor/github.com/denverdino/aliyungo/slb/listeners.go
  vendor/github.com/denverdino/aliyungo/slb/vserver_group.go
  vendor/github.com/go-cmd/cmd/LICENSE
  vendor/github.com/go-cmd/cmd/README.md
  vendor/github.com/go-cmd/cmd/cmd.go
  vendor/github.com/go-cmd/cmd/cmd_test.go
Labels: cncf-cla: yes, size/XXL

#64 [ADD] add ModifyLoadBalancerInstanceSpec
  cloud-controller-manager/loadbalancer.go
  cloud-controller-manager/loadbalancer_mock.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#65 E2ETest
  Makefile
  README.md
  cloud-controller-manager/alicloud.go
  cloud-controller-manager/alicloud_test.go
  cloud-controller-manager/controller/service/controller.go
  cloud-controller-manager/framework.go
  cloud-controller-manager/listener_test.go
  cloud-controller-manager/listeners.go
  cloud-controller-manager/loadbalancer.go
  cloud-controller-manager/loadbalancer_mock.go
  cloud-controller-manager/loadbalancer_test.go
  cloud-controller-manager/privatezone.go
  cloud-controller-manager/utils.go
  cloud-controller-manager/utils/log.go
  cloud-controller-manager/utils/tool.go
  cloud-controller-manager/vgroups.go
  cmd/e2e/README.md
  cmd/e2e/e2e_test.go
  cmd/e2e/framework/actions.go
  cmd/e2e/framework/cloud.go
  cmd/e2e/framework/flags.go
  cmd/e2e/framework/framework.go
  cmd/e2e/test/service.go
  docs/dev.md
  docs/testing.md
Labels: cncf-cla: yes, size/XXL

#66 e2etest makefile
  Makefile
  cloud-controller-manager/loadbalancer.go
  cmd/e2e/e2e_test.go
  cmd/e2e/framework/framework.go
  cmd/e2e/test/service.go
Labels: cncf-cla: yes

#67 privatezone support ipv6 loadbalancer
  cloud-controller-manager/alicloud.go
  cloud-controller-manager/privatezone.go
Labels: cncf-cla: yes, ok-to-test, size/M

#69 fix gometalinter issues
  cloud-controller-manager/controller/service/controller.go
  cloud-controller-manager/framework.go
  cloud-controller-manager/instances.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#75 complete e2e test cases
  cloud-controller-manager/controller/node/controller.go
  cloud-controller-manager/framework.go
  cloud-controller-manager/privatezone.go
  cloud-controller-manager/utils/log.go
  cloud-controller-manager/vgroups.go
  cmd/e2e/e2e_test.go
  cmd/e2e/framework/actions.go
  cmd/e2e/framework/flags.go
  cmd/e2e/framework/framework.go
  cmd/e2e/test/combination.go
  cmd/e2e/test/service.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL
