Repository kubernetes/cloud-provider-alibaba-cloud, pull requests merged in 2020-02, with the labels that each got.

#143 change the key of route cache
  cloud-controller-manager/controller/route/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#104 Adding documentation for rke set up and other documentation updates
  cloud-controller-manager/instances.go
  docs/getting-started.md
Labels: approved, cncf-cla: yes, lgtm, lifecycle/rotten, ok-to-test, size/M

#145 Update readme.txt
  docs/usage.md
  docs/zh/usage.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#146 fix-nodename-nil
  cloud-controller-manager/vgroups.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#147 fix nodename nil error
  cloud-controller-manager/vgroups.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
