Repository kubernetes/cloud-provider-alibaba-cloud, pull requests merged in 2020-05, with the labels that each got.

#156 add logs about endpoints
  cloud-controller-manager/controller/service/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#158 add debug info for node change event
  cloud-controller-manager/controller/service/context.go
Labels: cncf-cla: yes, size/S

#159 Ctx.route
  cloud-controller-manager/alicloud_test.go
  cloud-controller-manager/controller/node/controller.go
  cloud-controller-manager/controller/node/controller_test.go
  go.mod
  go.sum
Labels: cncf-cla: yes, size/S

#164 change the pagesize of DescribeNetworkInterfaces api to 100
  cloud-controller-manager/vgroups.go
Labels: cncf-cla: yes, size/XS

#153 new way to canculate the weight of nodes
  cloud-controller-manager/vgroups.go
Labels: cncf-cla: yes, size/XS

#161 can not reuse apiserver loadbalancer
  cloud-controller-manager/loadbalancer.go
Labels: cncf-cla: yes, size/S

#163 add prom metrics
  cloud-controller-manager/controller/node/controller.go
  cloud-controller-manager/controller/route/controller.go
  cloud-controller-manager/controller/service/controller.go
  cloud-controller-manager/utils/metric/node.go
  cloud-controller-manager/utils/metric/route.go
  cloud-controller-manager/utils/metric/slb.go
  cloud-controller-manager/utils/metric/util.go
  cmd/cloudprovider/app/ccm.go
Labels: cncf-cla: yes, size/M

#162 add events for slb
  cloud-controller-manager/controller/node/controller.go
  cloud-controller-manager/controller/route/controller.go
  cloud-controller-manager/controller/service/context.go
  cloud-controller-manager/controller/service/controller.go
Labels: cncf-cla: yes, size/L

#168 update function findLoadBalancerByID
  cloud-controller-manager/loadbalancer.go
  cloud-controller-manager/loadbalancer_mock.go
Labels: cncf-cla: yes, size/M

#167 publish route to cen
  cloud-controller-manager/alicloud.go
  cloud-controller-manager/alicloud_test.go
  cloud-controller-manager/cen.go
  cloud-controller-manager/clientmgr.go
  cloud-controller-manager/contextedclient.go
  cloud-controller-manager/controller/node/controller_test.go
  cloud-controller-manager/controller/route/controller.go
  cloud-controller-manager/routes.go
  go.mod
  go.sum
Labels: cncf-cla: yes, size/L

#169 Revert "publish route to cen"
  cloud-controller-manager/alicloud.go
  cloud-controller-manager/alicloud_test.go
  cloud-controller-manager/cen.go
  cloud-controller-manager/clientmgr.go
  cloud-controller-manager/contextedclient.go
  cloud-controller-manager/controller/node/controller_test.go
  cloud-controller-manager/controller/route/controller.go
  cloud-controller-manager/routes.go
  go.mod
  go.sum
Labels: cncf-cla: yes, size/L

#170 do not delete route for node which has the exlude label
  cloud-controller-manager/controller/route/controller.go
Labels: cncf-cla: yes, size/XS
