Repository kubernetes/cloud-provider-alibaba-cloud, pull requests merged in 2022-03, with the labels that each got.

#283 contentType change to proto
  cmd/manager/main.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#284 update weight
  pkg/controller/service/vgroups.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#285 add check for whether rsp belongs to the slb
  pkg/controller/service/vgroups.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#286 Feature/openapi
  pkg/controller/service/model_applier.go
  pkg/controller/service/vgroups.go
  pkg/provider/alibaba/slb/vgroup.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#288 support service.status.ingress.hostname
  pkg/controller/service/annotations.go
  pkg/controller/service/helper.go
  pkg/controller/service/service_controller.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#292 Feature/dryrun
  pkg/controller/service/listeners.go
  pkg/model/load_balancer.go
  pkg/provider/dryrun/event.go
  pkg/provider/dryrun/slb.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#291 support annotations:
  pkg/controller/service/annotations.go
  pkg/controller/service/listeners.go
  pkg/model/load_balancer.go
  pkg/provider/alibaba/slb/listener.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#293 fix bug: slb backend is nil when no endpoints in Cluster Mode
  pkg/controller/service/vgroups.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#287 return error if find multiple slb
  pkg/provider/alibaba/slb/loadbalancer.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#289 update VswitchID() func
  Makefile
  pkg/provider/alibaba/base/metadata.go
  pkg/provider/alibaba/base/metadata_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#290 add lbid for event
  cmd/manager/main.go
  pkg/controller/node/manager.go
  pkg/controller/service/model_applier.go
  pkg/controller/service/service_controller.go
  pkg/model/load_balancer.go
  pkg/model/load_balancer_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#272 Add PR and issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/failing-test.md
  .github/ISSUE_TEMPLATE/flaking-test.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cncf-cla: yes, lgtm, approved, needs-ok-to-test, size/L

#295 Bugfix/load listener resp
  pkg/provider/alibaba/slb/listener.go
  pkg/provider/alibaba/slb/loadbalancer.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#296 add e2etests for new annotations
  e2e/framework/expect.go
  e2e/framework/framework.go
  e2e/options/options.go
  e2e/testcase/node/node.go
  e2e/testcase/route/route.go
  e2e/testcase/service/listener.go
  e2e/testcase/service/loadbalancer.go
  pkg/provider/alibaba/slb/loadbalancer.go
Labels: cncf-cla: yes, approved, size/L

#297 feature/support-mulit-arch-build
  Dockerfile
  Makefile
  deploy/v1/cloud-controller-manager.yaml
  deploy/v2/cloud-controller-manager.yaml
Labels: cncf-cla: yes, lgtm, approved, size/XL
