Repository kubernetes/cloud-provider-alibaba-cloud, pull requests merged in 2022-06, with the labels that each got.

#303 update dryrun
  pkg/controller/service/service_controller.go
  pkg/model/load_balancer.go
  pkg/provider/dryrun/slb.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#305 update regexp
  pkg/controller/helper/event.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#306 support custom endpoints
  pkg/provider/alibaba/base/clientMgr.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#308 add slb id label for service
  pkg/controller/service/const.go
  pkg/controller/service/service_controller.go
  pkg/model/load_balancer.go
  pkg/model/load_balancer_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#309 fix do not delete conflict route with same cidr;update warning events
  pkg/controller/route/manager.go
  pkg/controller/route/route_controller.go
  pkg/provider/alibaba/vpc/vpc.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#282 patch providerid by node ip
  pkg/config/cloud_config.go
  pkg/controller/node/manager.go
  pkg/controller/node/node_controller.go
  pkg/controller/service/annotations.go
  pkg/controller/service/helper.go
  pkg/provider/alibaba/base/clientMgr.go
  pkg/provider/alibaba/ecs/ecs.go
  pkg/provider/dryrun/ecs.go
  pkg/provider/provider.go
  pkg/provider/vmock/ecs.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#314 fix no ip bug; add event if not find ecs according to ip
  pkg/controller/node/manager.go
  pkg/controller/node/node_controller.go
  pkg/provider/alibaba/ecs/ecs.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#316 test: skip vk node in node test
  test/e2e/client/kubeclient.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#322 fix wrong cluster id
  pkg/config/cloud_config.go
  pkg/controller/ingress/reconcile/applier/service.go
  pkg/controller/ingress/reconcile/tracking/tracking.go
  pkg/controller/service/annotations.go
  pkg/controller/service/helper.go
  pkg/provider/alibaba/base/clientMgr.go
  pkg/provider/alibaba/base/metadata.go
  pkg/provider/alibaba/ecs/ecs.go
  pkg/util/constant.go
Labels: cncf-cla: yes, lgtm, approved, size/M
