Repository kubernetes/cloud-provider-alibaba-cloud, pull requests merged in 2023-06, with the labels that each got.

#359 fix: when a service with eip annotation, it can not be updated.
  pkg/controller/service/clbv1/model_applier.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#360 fix: divide by zero
  pkg/controller/service/clbv1/vgroups.go
  pkg/controller/service/nlbv2/server_groups.go
  test/e2e/framework/expect.go
  test/e2e/framework/expect_nlb.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#361 fix: http annotation can not work when the service already has forwar…
  pkg/controller/service/clbv1/listeners.go
  test/e2e/testcase/service/clbv1/listener.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#362 feat: STS and NLB products use vpc endpoint
  pkg/provider/alibaba/base/clientMgr.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#363 feat: update compute hash func
  pkg/controller/helper/service_utils.go
  pkg/controller/helper/service_utils_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#364 feat: update controllerCFG
  pkg/controller/node/node_controller.go
  pkg/controller/service/clbv1/service_controller.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#365 feat: aggregate errors when sync clb&nlb backend servers
  pkg/controller/helper/event.go
  pkg/controller/service/clbv1/vgroups.go
  pkg/controller/service/clbv1/vgroups_test.go
  pkg/controller/service/nlbv2/server_groups.go
  pkg/controller/service/reconcile/backend/backend.go
  pkg/model/load_balancer.go
  pkg/model/nlb/nlb.go
  pkg/provider/vmock/slb.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#366 Support specify CLB ip address in annotation
  pkg/controller/service/clbv1/loadbalancer.go
  pkg/controller/service/reconcile/annotation/annotations.go
  pkg/model/load_balancer.go
  pkg/provider/alibaba/slb/loadbalancer.go
  test/e2e/framework/expect.go
  test/e2e/options/options.go
  test/e2e/testcase/service/clbv1/loadbalancer.go
Labels: kind/feature, cncf-cla: yes, lgtm, approved, size/M, needs-ok-to-test
