Repository kubernetes/cloud-provider-alibaba-cloud, pull requests merged in 2023-10, with the labels that each got.

#370 fix: typo in loadbalancer
  pkg/provider/alibaba/elb/loadbalancer.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-ok-to-test

#368 chore: replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`
  go.mod
  go.sum
  pkg/config/cloud_config.go
  pkg/util/hash/hash.go
  vendor/github.com/ghodss/yaml/.gitignore
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, kind/cleanup, needs-ok-to-test, size/XL

#374 Bugfix/servergroup
  go.mod
  go.sum
  pkg/controller/service/nlbv2/server_groups.go
  pkg/provider/alibaba/nlb/loadbalancer.go
  pkg/provider/alibaba/nlb/servergroup.go
  vendor/github.com/alibabacloud-go/nlb-20220430/client/client.go
  vendor/github.com/alibabacloud-go/tea-utils/v2/service/service.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, approved, size/XXL

#375 Bugfix/no cache for node
  pkg/config/runtime_config.go
  pkg/controller/helper/endpoint_utils.go
  pkg/controller/service/clbv1/event_handler.go
  pkg/controller/service/clbv1/event_handler_test.go
  pkg/controller/service/clbv1/service_controller.go
  pkg/controller/service/clbv1/service_controller_test.go
  pkg/controller/service/clbv1/vgroups.go
  pkg/controller/service/elb/elb_controller.go
  pkg/controller/service/elb/event_handler.go
  pkg/controller/service/nlbv2/event_handler.go
  pkg/controller/service/nlbv2/event_handler_test.go
  pkg/controller/service/nlbv2/nlb_controller_test.go
  pkg/controller/service/nlbv2/server_groups.go
  pkg/controller/service/reconcile/backend/backend.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#377 feat: filter pods whose ip not in vpc cidr in eni mod
  pkg/controller/service/clbv1/service_controller_test.go
  pkg/controller/service/clbv1/vgroups.go
  pkg/provider/alibaba/vpc/vpc.go
  pkg/provider/dryrun/vpc.go
  pkg/provider/provider.go
  pkg/provider/vmock/vpc.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#380 Feature/addon token
  pkg/provider/alibaba/base/clientMgr.go
  pkg/provider/alibaba/base/token.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#381 support configuring server group batch size
  pkg/config/controller_config.go
  pkg/controller/service/clbv1/vgroups.go
  pkg/controller/service/nlbv2/server_groups.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#382 test: update route controller tests
  pkg/controller/route/route_controller_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#379 Feature/ip mode
  pkg/controller/helper/node_utils.go
  pkg/controller/service/clbv1/model_applier.go
  pkg/controller/service/nlbv2/model_applier.go
  pkg/controller/service/nlbv2/server_groups.go
  pkg/controller/service/reconcile/annotation/annotations.go
  pkg/provider/alibaba/nlb/listener.go
  pkg/provider/alibaba/nlb/loadbalancer.go
  pkg/provider/alibaba/nlb/servergroup.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#384 add nlb ip tests; update expect to support paybyclcu & serverGroupTDype
  test/e2e/e2e_test.go
  test/e2e/framework/expect.go
  test/e2e/framework/expect_nlb.go
  test/e2e/testcase/service/clbv1/loadbalancer.go
  test/e2e/testcase/service/nlbv2/backend.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#387 support vpc with secondary cidrs
  pkg/controller/helper/event.go
  pkg/controller/service/clbv1/vgroups.go
  pkg/provider/alibaba/vpc/vpc.go
  pkg/provider/dryrun/vpc.go
  pkg/provider/provider.go
  pkg/provider/vmock/vpc.go
Labels: cncf-cla: yes, lgtm, approved, size/L
