Repository kubernetes/cloud-provider-alibaba-cloud, pull requests merged in 2023-02, with the labels that each got.

#336 Remove unused circleci config
  .circleci/config.yml
Labels: cncf-cla: yes, lgtm, size/M

#349 upgrade golangci-lint to v1.51.2
  Makefile
  go.mod
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#338 remove serverip when type=ecs
  pkg/controller/service/clbv1/vgroups.go
  pkg/controller/service/nlbv2/server_groups.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#340 update LabelNodeExcludeBalancers
  pkg/controller/helper/node_utils.go
  test/e2e/client/kubeclient.go
  test/e2e/framework/expect.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#348 do not update cert if cert is expired
  pkg/controller/service/clbv1/listeners.go
  pkg/model/load_balancer.go
  pkg/provider/alibaba/slb/cert.go
  pkg/provider/alibaba/slb/loadbalancer.go
  pkg/provider/dryrun/slb.go
  pkg/provider/provider.go
  pkg/provider/vmock/slb.go
Labels: kind/feature, cncf-cla: yes, lgtm, approved, size/L

#350 do not create/add vservergroup in precheck
  pkg/provider/dryrun/slb.go
Labels: kind/feature, cncf-cla: yes, lgtm, approved, size/S

#343 feature: support close udp/tcp health check
  pkg/controller/service/clbv1/listeners.go
  pkg/controller/service/reconcile/annotation/annotations.go
  pkg/model/load_balancer.go
  pkg/provider/alibaba/slb/listener.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#351 add ascm context when creating slb
  pkg/provider/alibaba/slb/loadbalancer.go
Labels: kind/feature, cncf-cla: yes, size/XS, lgtm, approved

#344 support tcp/udp mixed protocol
  pkg/controller/service/clbv1/listeners.go
  pkg/provider/alibaba/slb/listener.go
  pkg/provider/dryrun/slb.go
  pkg/provider/provider.go
  pkg/provider/vmock/slb.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#342 Feature/nlb security group
  go.mod
  go.sum
  pkg/controller/service/nlbv2/loadbalancer.go
  pkg/controller/service/nlbv2/model_applier.go
  pkg/controller/service/reconcile/annotation/annotations.go
  pkg/model/nlb/nlb.go
  pkg/provider/alibaba/nlb/loadbalancer.go
  pkg/provider/dryrun/nlb.go
  pkg/provider/provider.go
  pkg/provider/vmock/nlb.go
  test/e2e/framework/expect_nlb.go
  test/e2e/options/options.go
  test/e2e/testcase/service/nlbv2/loadbalancer.go
  vendor/github.com/alibabacloud-go/darabonba-openapi/v2/client/client.go
  vendor/github.com/alibabacloud-go/nlb-20220430/client/client.go
  vendor/github.com/alibabacloud-go/tea-utils/v2/service/service.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, approved, size/XXL

#352 update owners
  OWNERS
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/documentation

#341 if sync lb failed, continue to sync vgroup & listener
  pkg/controller/service/clbv1/loadbalancer.go
  pkg/controller/service/clbv1/model_applier.go
  pkg/controller/service/nlbv2/loadbalancer.go
  pkg/controller/service/nlbv2/model_applier.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#353 add e2etests
  test/e2e/client/kubeclient.go
  test/e2e/framework/expect_nlb.go
  test/e2e/framework/framework.go
  test/e2e/testcase/route/route.go
  test/e2e/testcase/service/clbv1/backend.go
  test/e2e/testcase/service/clbv1/listener.go
  test/e2e/testcase/service/nlbv2/backend.go
  test/e2e/testcase/service/nlbv2/listener.go
Labels: cncf-cla: yes, lgtm, approved, size/L
