Repository kubernetes/cloud-provider-alibaba-cloud, pull requests merged in 2024-03, with the labels that each got.

#405 add resourceVersion=0 for list requests
  pkg/controller/node/manager.go
  pkg/controller/service/clbv1/event_handler.go
  pkg/controller/service/nlbv2/event_handler.go
  pkg/controller/service/reconcile/backend/backend.go
Labels: kind/feature, cncf-cla: yes, lgtm, approved, needs-ok-to-test, size/S

#398 set HealthCheckInterval to 5 to fix e2e error
  test/e2e/testcase/service/nlbv2/backend.go
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved, kind/failing-test, needs-ok-to-test

#406 bugfix: fix node controller do not init routeconfig
  pkg/controller/node/manager.go
  pkg/controller/node/node_controller.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#396 enable EndpointSlice feature by default
  pkg/config/feature_gates.go
Labels: kind/feature, cncf-cla: yes, size/XS, lgtm, approved, needs-ok-to-test

#397 filter services when node reconcile
  pkg/config/feature_gates.go
  pkg/controller/service/clbv1/event_handler.go
  pkg/controller/service/nlbv2/event_handler.go
Labels: kind/feature, cncf-cla: yes, lgtm, approved, size/M, needs-ok-to-test

#395 node add ipv6 address
  pkg/controller/helper/net_utils.go
  pkg/controller/helper/node_utils.go
  pkg/controller/node/node_controller.go
  pkg/provider/alibaba/ecs/ecs.go
Labels: kind/feature, cncf-cla: yes, lgtm, approved, needs-ok-to-test, size/L

#393 check loadbalancer id from API when reuse
  pkg/provider/alibaba/nlb/loadbalancer.go
  pkg/provider/alibaba/slb/loadbalancer.go
Labels: cncf-cla: yes, lgtm, approved, needs-ok-to-test, size/S

#394 create with specified resource group id for clb&nlb
  pkg/config/cloud_config.go
  pkg/controller/route/manager.go
  pkg/controller/route/manager_test.go
  pkg/controller/service/clbv1/loadbalancer.go
  pkg/controller/service/nlbv2/loadbalancer.go
  pkg/controller/service/nlbv2/server_groups.go
  pkg/provider/alibaba/nlb/servergroup.go
Labels: cncf-cla: yes, lgtm, approved, size/M, needs-ok-to-test

#401 add node max syncs in cloud config
  pkg/config/cloud_config.go
  pkg/config/controller_config.go
  pkg/controller/node/event_handler.go
  pkg/controller/node/node_controller.go
  pkg/controller/service/clbv1/service_controller.go
  pkg/controller/service/nlbv2/nlb_controller.go
  pkg/util/log.go
Labels: kind/feature, cncf-cla: yes, lgtm, approved, size/M

#403 feat: support reusing nlb of another vpc
  pkg/controller/service/nlbv2/model_applier.go
  pkg/provider/alibaba/nlb/loadbalancer.go
Labels: kind/feature, cncf-cla: yes, size/XS, lgtm, approved

#390 upgrade nlb sdk to v3.0.0 & support nlb ppv2 privatelink
  go.mod
  go.sum
  pkg/controller/service/nlbv2/listeners.go
  pkg/controller/service/reconcile/annotation/annotations.go
  pkg/model/nlb/nlb.go
  pkg/provider/alibaba/base/clientMgr.go
  pkg/provider/alibaba/nlb/listener.go
  pkg/provider/alibaba/nlb/loadbalancer.go
  pkg/provider/alibaba/nlb/loadbalancer_test.go
  pkg/provider/alibaba/nlb/servergroup.go
  pkg/provider/alibaba/nlb/servergroup_test.go
  test/e2e/framework/expect_nlb.go
  test/e2e/testcase/service/nlbv2/listener.go
  vendor/github.com/alibabacloud-go/nlb-20220430/v3/LICENSE
  vendor/github.com/alibabacloud-go/nlb-20220430/v3/client/client.go
  vendor/modules.txt
Labels: kind/feature, cncf-cla: yes, lgtm, approved, lifecycle/stale, size/XXL, needs-ok-to-test

#391 nlb ipv6 backend & address type support
  pkg/controller/service/nlbv2/loadbalancer.go
  pkg/controller/service/nlbv2/model_applier.go
  pkg/controller/service/nlbv2/server_groups.go
  pkg/controller/service/reconcile/annotation/annotations.go
  pkg/controller/service/reconcile/backend/backend.go
  pkg/model/nlb/nlb.go
  pkg/provider/alibaba/ecs/ecs.go
  pkg/provider/alibaba/nlb/loadbalancer.go
  pkg/provider/dryrun/nlb.go
  pkg/provider/provider.go
  pkg/provider/vmock/nlb.go
  test/e2e/framework/expect_nlb.go
  test/e2e/options/options.go
  test/e2e/testcase/service/nlbv2/loadbalancer.go
Labels: kind/feature, cncf-cla: yes, lgtm, approved, needs-ok-to-test, size/L

#392 support nlb vgroup-port and weight & fix clb listener vgroup reuse
  pkg/controller/service/clbv1/listeners.go
  pkg/controller/service/clbv1/vgroups.go
  pkg/controller/service/nlbv2/listeners.go
  pkg/controller/service/nlbv2/model_applier.go
  pkg/controller/service/nlbv2/server_groups.go
  pkg/provider/alibaba/nlb/servergroup.go
  pkg/provider/dryrun/nlb.go
  pkg/provider/provider.go
  pkg/provider/vmock/nlb.go
  test/e2e/framework/expect_nlb.go
  test/e2e/options/options.go
  test/e2e/testcase/service/nlbv2/backend.go
Labels: kind/feature, cncf-cla: yes, lgtm, approved, needs-ok-to-test, size/XL

#404 [Bug] Optimize ZoneMappings comparison
  pkg/controller/service/nlbv2/loadbalancer.go
Labels: kind/bug, cncf-cla: yes, lgtm, approved, needs-ok-to-test, size/S
